[2024-06-18T13:30:55.374+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T13:30:55.391+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_analytics_database_v3.load_data manual__2024-06-18T13:30:52.750057+00:00 [queued]>
[2024-06-18T13:30:55.396+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_analytics_database_v3.load_data manual__2024-06-18T13:30:52.750057+00:00 [queued]>
[2024-06-18T13:30:55.396+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-18T13:30:55.405+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2024-06-18 13:30:52.750057+00:00
[2024-06-18T13:30:55.409+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6436) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-18T13:30:55.410+0000] {standard_task_runner.py:63} INFO - Started process 6437 to run task
[2024-06-18T13:30:55.411+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_to_analytics_database_v3', 'load_data', 'manual__2024-06-18T13:30:52.750057+00:00', '--job-id', '757', '--raw', '--subdir', 'DAGS_FOLDER/batch-processing_dag.py', '--cfg-path', '/tmp/tmprqbp9lju']
[2024-06-18T13:30:55.411+0000] {standard_task_runner.py:91} INFO - Job 757: Subtask load_data
[2024-06-18T13:30:55.440+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_to_analytics_database_v3.load_data manual__2024-06-18T13:30:52.750057+00:00 [running]> on host 195daacf7793
[2024-06-18T13:30:55.490+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_to_analytics_database_v3' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T13:30:52.750057+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T13:30:52.750057+00:00'
[2024-06-18T13:30:55.491+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T13:30:55.511+0000] {base.py:84} INFO - Using connection ID 'analytics_localhost' for task execution.
[2024-06-18T13:30:55.522+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T13:30:55.523+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/batch-processing_dag.py", line 121, in load_data
    expense['user_id'] = cursor.fetchone()[0]
                         ~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
[2024-06-18T13:30:55.530+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_to_analytics_database_v3, task_id=load_data, run_id=manual__2024-06-18T13:30:52.750057+00:00, execution_date=20240618T133052, start_date=20240618T133055, end_date=20240618T133055
[2024-06-18T13:30:55.538+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 757 for task load_data ('NoneType' object is not subscriptable; 6437)
[2024-06-18T13:30:55.584+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T13:30:55.595+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T13:30:55.597+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
