[2024-06-18T13:11:27.991+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T13:11:28.007+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_analytics_database.transform_data manual__2024-06-18T13:11:26.552121+00:00 [queued]>
[2024-06-18T13:11:28.012+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_analytics_database.transform_data manual__2024-06-18T13:11:26.552121+00:00 [queued]>
[2024-06-18T13:11:28.013+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-18T13:11:28.021+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2024-06-18 13:11:26.552121+00:00
[2024-06-18T13:11:28.025+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6143) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-18T13:11:28.026+0000] {standard_task_runner.py:63} INFO - Started process 6144 to run task
[2024-06-18T13:11:28.026+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_to_analytics_database', 'transform_data', 'manual__2024-06-18T13:11:26.552121+00:00', '--job-id', '740', '--raw', '--subdir', 'DAGS_FOLDER/batch-processing_dag.py', '--cfg-path', '/tmp/tmpw5yf56b2']
[2024-06-18T13:11:28.027+0000] {standard_task_runner.py:91} INFO - Job 740: Subtask transform_data
[2024-06-18T13:11:28.055+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_to_analytics_database.transform_data manual__2024-06-18T13:11:26.552121+00:00 [running]> on host 195daacf7793
[2024-06-18T13:11:28.103+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_to_analytics_database' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T13:11:26.552121+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T13:11:26.552121+00:00'
[2024-06-18T13:11:28.104+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T13:11:28.120+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T13:11:28.120+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/batch-processing_dag.py", line 46, in transform_data
    dim_users = [{'id': u[0], 'username': u[1], 'role': role_map[u[3]]} for u in users]
                                                        ~~~~~~~~^^^^^^
KeyError: 'weekly'
[2024-06-18T13:11:28.127+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_to_analytics_database, task_id=transform_data, run_id=manual__2024-06-18T13:11:26.552121+00:00, execution_date=20240618T131126, start_date=20240618T131128, end_date=20240618T131128
[2024-06-18T13:11:28.135+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 740 for task transform_data ('weekly'; 6144)
[2024-06-18T13:11:28.159+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T13:11:28.174+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T13:11:28.177+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
