[2024-06-18T12:51:43.488+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T12:51:43.505+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_analytics_database.extract_data_from_staging manual__2024-06-18T12:51:42.807591+00:00 [queued]>
[2024-06-18T12:51:43.510+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_analytics_database.extract_data_from_staging manual__2024-06-18T12:51:42.807591+00:00 [queued]>
[2024-06-18T12:51:43.511+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-18T12:51:43.521+0000] {taskinstance.py:2330} INFO - Executing <Task(MySqlOperator): extract_data_from_staging> on 2024-06-18 12:51:42.807591+00:00
[2024-06-18T12:51:43.525+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5847) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-18T12:51:43.526+0000] {standard_task_runner.py:63} INFO - Started process 5848 to run task
[2024-06-18T12:51:43.526+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_to_analytics_database', 'extract_data_from_staging', 'manual__2024-06-18T12:51:42.807591+00:00', '--job-id', '726', '--raw', '--subdir', 'DAGS_FOLDER/batch-processing_dag.py', '--cfg-path', '/tmp/tmpk8ik5s2n']
[2024-06-18T12:51:43.527+0000] {standard_task_runner.py:91} INFO - Job 726: Subtask extract_data_from_staging
[2024-06-18T12:51:43.558+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_to_analytics_database.extract_data_from_staging manual__2024-06-18T12:51:42.807591+00:00 [running]> on host 195daacf7793
[2024-06-18T12:51:43.612+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_to_analytics_database' AIRFLOW_CTX_TASK_ID='extract_data_from_staging' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T12:51:42.807591+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T12:51:42.807591+00:00'
[2024-06-18T12:51:43.613+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T12:51:43.622+0000] {sql.py:276} INFO - Executing: 
    SELECT * FROM roles;
    SELECT * FROM users;
    SELECT * FROM expense;
    SELECT * FROM income;
    SELECT * FROM expense_groups;
    SELECT * FROM income_groups;
    
[2024-06-18T12:51:43.628+0000] {base.py:84} INFO - Using connection ID 'mysql_localhost' for task execution.
[2024-06-18T12:51:43.632+0000] {base.py:84} INFO - Using connection ID 'mysql_localhost' for task execution.
[2024-06-18T12:51:43.639+0000] {sql.py:487} INFO - Running statement: 
    SELECT * FROM roles;
    SELECT * FROM users;
    SELECT * FROM expense;
    SELECT * FROM income;
    SELECT * FROM expense_groups;
    SELECT * FROM income_groups;
    , parameters: None
[2024-06-18T12:51:43.639+0000] {sql.py:496} INFO - Rows affected: 2
[2024-06-18T12:51:43.642+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T12:51:43.643+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 432, in run
    with closing(conn.cursor()) as cur:
  File "/usr/local/lib/python3.12/contextlib.py", line 360, in __exit__
    self.thing.close()
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 103, in close
    self._discard()
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 95, in _discard
    while con.next_result() == 0:  # -1 means no more data.
          ^^^^^^^^^^^^^^^^^
MySQLdb.ProgrammingError: (1146, "Table 'testdb.expense_groups' doesn't exist")
[2024-06-18T12:51:43.649+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_to_analytics_database, task_id=extract_data_from_staging, run_id=manual__2024-06-18T12:51:42.807591+00:00, execution_date=20240618T125142, start_date=20240618T125143, end_date=20240618T125143
[2024-06-18T12:51:43.657+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 726 for task extract_data_from_staging ((1146, "Table 'testdb.expense_groups' doesn't exist"); 5848)
[2024-06-18T12:51:43.700+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T12:51:43.707+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class MySqlOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-06-18T12:51:43.715+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T12:51:43.718+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
