[2024-06-19T08:26:11.211+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T08:26:11.227+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_analytics_database_v3.load_data manual__2024-06-19T08:26:08.224439+00:00 [queued]>
[2024-06-19T08:26:11.233+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_analytics_database_v3.load_data manual__2024-06-19T08:26:08.224439+00:00 [queued]>
[2024-06-19T08:26:11.233+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-19T08:26:11.242+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2024-06-19 08:26:08.224439+00:00
[2024-06-19T08:26:11.246+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=21540) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-19T08:26:11.247+0000] {standard_task_runner.py:63} INFO - Started process 21541 to run task
[2024-06-19T08:26:11.247+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_to_analytics_database_v3', 'load_data', 'manual__2024-06-19T08:26:08.224439+00:00', '--job-id', '776', '--raw', '--subdir', 'DAGS_FOLDER/batch-processing_dag.py', '--cfg-path', '/tmp/tmpx2l6zhdz']
[2024-06-19T08:26:11.248+0000] {standard_task_runner.py:91} INFO - Job 776: Subtask load_data
[2024-06-19T08:26:11.277+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_to_analytics_database_v3.load_data manual__2024-06-19T08:26:08.224439+00:00 [running]> on host 195daacf7793
[2024-06-19T08:26:11.331+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_to_analytics_database_v3' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T08:26:08.224439+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T08:26:08.224439+00:00'
[2024-06-19T08:26:11.332+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T08:26:11.354+0000] {base.py:84} INFO - Using connection ID 'analytics_localhost' for task execution.
[2024-06-19T08:26:11.375+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-19T08:26:11.376+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T08:26:11.382+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_to_analytics_database_v3, task_id=load_data, run_id=manual__2024-06-19T08:26:08.224439+00:00, execution_date=20240619T082608, start_date=20240619T082611, end_date=20240619T082611
[2024-06-19T08:26:11.421+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-19T08:26:11.431+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T08:26:11.433+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
