[2024-06-19T08:38:02.587+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T08:38:02.604+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_analytics_database_v3.load_data manual__2024-06-19T08:38:00.052290+00:00 [queued]>
[2024-06-19T08:38:02.610+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_analytics_database_v3.load_data manual__2024-06-19T08:38:00.052290+00:00 [queued]>
[2024-06-19T08:38:02.611+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-19T08:38:02.621+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2024-06-19 08:38:00.052290+00:00
[2024-06-19T08:38:02.625+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=21698) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-19T08:38:02.626+0000] {standard_task_runner.py:63} INFO - Started process 21699 to run task
[2024-06-19T08:38:02.626+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_to_analytics_database_v3', 'load_data', 'manual__2024-06-19T08:38:00.052290+00:00', '--job-id', '779', '--raw', '--subdir', 'DAGS_FOLDER/batch-processing_dag.py', '--cfg-path', '/tmp/tmp8vx5f072']
[2024-06-19T08:38:02.627+0000] {standard_task_runner.py:91} INFO - Job 779: Subtask load_data
[2024-06-19T08:38:02.661+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_to_analytics_database_v3.load_data manual__2024-06-19T08:38:00.052290+00:00 [running]> on host 195daacf7793
[2024-06-19T08:38:02.725+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_to_analytics_database_v3' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T08:38:00.052290+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T08:38:00.052290+00:00'
[2024-06-19T08:38:02.726+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T08:38:02.751+0000] {base.py:84} INFO - Using connection ID 'analytics_localhost' for task execution.
[2024-06-19T08:38:02.844+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-19T08:38:02.845+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T08:38:02.852+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_to_analytics_database_v3, task_id=load_data, run_id=manual__2024-06-19T08:38:00.052290+00:00, execution_date=20240619T083800, start_date=20240619T083802, end_date=20240619T083802
[2024-06-19T08:38:02.880+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-19T08:38:02.891+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T08:38:02.893+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
