[2024-06-18T13:25:55.689+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T13:25:55.705+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_analytics_database_v3.load_data manual__2024-06-18T13:25:53.183951+00:00 [queued]>
[2024-06-18T13:25:55.711+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_analytics_database_v3.load_data manual__2024-06-18T13:25:53.183951+00:00 [queued]>
[2024-06-18T13:25:55.711+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-18T13:25:55.721+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2024-06-18 13:25:53.183951+00:00
[2024-06-18T13:25:55.725+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6356) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-18T13:25:55.726+0000] {standard_task_runner.py:63} INFO - Started process 6357 to run task
[2024-06-18T13:25:55.726+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_to_analytics_database_v3', 'load_data', 'manual__2024-06-18T13:25:53.183951+00:00', '--job-id', '751', '--raw', '--subdir', 'DAGS_FOLDER/batch-processing_dag.py', '--cfg-path', '/tmp/tmp3fw0nrgi']
[2024-06-18T13:25:55.727+0000] {standard_task_runner.py:91} INFO - Job 751: Subtask load_data
[2024-06-18T13:25:55.758+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_to_analytics_database_v3.load_data manual__2024-06-18T13:25:53.183951+00:00 [running]> on host 195daacf7793
[2024-06-18T13:25:55.817+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_to_analytics_database_v3' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T13:25:53.183951+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T13:25:53.183951+00:00'
[2024-06-18T13:25:55.818+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T13:25:55.840+0000] {base.py:84} INFO - Using connection ID 'analytics_localhost' for task execution.
[2024-06-18T13:25:55.913+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T13:25:55.914+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/batch-processing_dag.py", line 117, in load_data
    expense['user_id'] = cursor.fetchone()[0]
                         ~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
[2024-06-18T13:25:55.922+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_to_analytics_database_v3, task_id=load_data, run_id=manual__2024-06-18T13:25:53.183951+00:00, execution_date=20240618T132553, start_date=20240618T132555, end_date=20240618T132555
[2024-06-18T13:25:55.930+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 751 for task load_data ('NoneType' object is not subscriptable; 6357)
[2024-06-18T13:25:55.939+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T13:25:55.949+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T13:25:55.951+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
