[2024-06-18T12:26:44.744+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T12:26:44.760+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_mysql_operator_v04.create_table manual__2024-06-18T12:26:43.481745+00:00 [queued]>
[2024-06-18T12:26:44.765+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_mysql_operator_v04.create_table manual__2024-06-18T12:26:43.481745+00:00 [queued]>
[2024-06-18T12:26:44.765+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-18T12:26:44.775+0000] {taskinstance.py:2330} INFO - Executing <Task(MySqlOperator): create_table> on 2024-06-18 12:26:43.481745+00:00
[2024-06-18T12:26:44.779+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5504) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-18T12:26:44.780+0000] {standard_task_runner.py:63} INFO - Started process 5505 to run task
[2024-06-18T12:26:44.780+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_mysql_operator_v04', 'create_table', 'manual__2024-06-18T12:26:43.481745+00:00', '--job-id', '719', '--raw', '--subdir', 'DAGS_FOLDER/mysql_dag.py', '--cfg-path', '/tmp/tmpvkoe2e6a']
[2024-06-18T12:26:44.781+0000] {standard_task_runner.py:91} INFO - Job 719: Subtask create_table
[2024-06-18T12:26:44.810+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_mysql_operator_v04.create_table manual__2024-06-18T12:26:43.481745+00:00 [running]> on host 195daacf7793
[2024-06-18T12:26:44.865+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_mysql_operator_v04' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T12:26:43.481745+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T12:26:43.481745+00:00'
[2024-06-18T12:26:44.866+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T12:26:44.874+0000] {sql.py:276} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2024-06-18T12:26:44.880+0000] {base.py:84} INFO - Using connection ID 'mysql_localhost' for task execution.
[2024-06-18T12:26:44.884+0000] {base.py:84} INFO - Using connection ID 'mysql_localhost' for task execution.
[2024-06-18T12:26:44.893+0000] {sql.py:487} INFO - Running statement: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        , parameters: None
[2024-06-18T12:26:44.894+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T12:26:44.894+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 435, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ',\n                primary key (dt, dag_id)\n            )' at line 3")
[2024-06-18T12:26:44.900+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_mysql_operator_v04, task_id=create_table, run_id=manual__2024-06-18T12:26:43.481745+00:00, execution_date=20240618T122643, start_date=20240618T122644, end_date=20240618T122644
[2024-06-18T12:26:44.908+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 719 for task create_table ((1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ',\n                primary key (dt, dag_id)\n            )' at line 3"); 5505)
[2024-06-18T12:26:44.954+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T12:26:44.960+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class MySqlOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-06-18T12:26:44.970+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T12:26:44.972+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
